### ISSUE TITLE
Update styles of the Gatsby blog to match webflow blog

### ISSUE THREAD

**Issue by st-jay** [supertokens/blog#27]
# Goal
We want the Gatsby blog to have styling consistent with the webflow blog.

# List of all inconsistencies
- Proper margin, padding, font size, font weight and font style
  - Headings
  - Paragraphs
  - Images
  - Lists and list items
  - Footnote text
- Footnote superscript link styling
- Indentation for list items
- `border-bottom` for headings

**Comment by rishabhpoddar** [comment]
Pushed to prod
