### ISSUE TITLE
Add sign up banner at the end of blogs

### ISSUE THREAD

**Issue by st-jay** [supertokens/blog#89]
## Goal
- Implement banner from frame 9 of the following design: 
 https://www.figma.com/file/Cy2eCZbmNZR3Debtl7wjo6/SuperTokens?node-id=63%3A190
- Should be added at the end of each blog post

**Comment by st-jay** [comment]
@mufassirkazi should this banner be added after the discord button at the end of a post?

**Comment by mufassirkazi** [comment]
> should this banner be added after the discord button at the end of a post?

Tell nevil to make a secondary discord button inside the banner and remove the current discord button

> What should be the analytics event for the button click?


Already there in the amplitude framework sheet at row 183

> How should it appear on mobile view?

Please ask nevil. Give him the below image as reference
<img width="279" alt="Screenshot 2022-07-19 at 9 55 58 PM" src="https://user-images.githubusercontent.com/46087290/179827532-b3b3cb22-19cf-41c6-a732-b2b65da3e5a5.png">

> Any hover effects for the 'Sign Up' button?

The same colour change when you hover over the sign up button on homepage
